"""AI opportunity templates, grounded to a specific (process, stage).

Every entry here maps to a real stage defined in processes.py. The opportunity
engine (app/engines/opportunity_engine.py) never generates a use case that
isn't rooted in one of these templates — it only adjusts the baseline scores
below using the user's actual assessment inputs. Stages with low AI
suitability (pure physical work, rubber-stamp approvals) intentionally have
no template: the product's premise is that AI should be proposed where it
genuinely fits, not everywhere.

Baseline fields (0-100, pre-adjustment):
  business_value_baseline           potential value if this opportunity is pursued
  technical_feasibility_baseline    how mature/available the required AI capability is
  implementation_complexity_baseline  higher = harder to build/integrate
  risk_baseline                     higher = more risk (accuracy, compliance, oversight)
  time_to_value_baseline            higher = faster to see value
"""

TEMPLATES = {
    # ---------------- Procure-to-Pay ----------------
    "procure_to_pay:purchase_order": {
        "use_case_name": "AI-Assisted Purchase Order Generation",
        "ai_capability": "Generative drafting + rules-based validation",
        "required_data": ["Requisition data", "Supplier catalog", "Pricing agreements"],
        "description": "AI drafts purchase orders from requisitions, auto-selecting supplier and pricing terms for review.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 80,
    },
    "procure_to_pay:invoice_receipt": {
        "use_case_name": "Intelligent Document Processing for Invoices",
        "ai_capability": "Document AI (OCR + extraction) for unstructured invoices",
        "required_data": ["Historical invoices", "Vendor master data", "Email/PDF archive"],
        "description": "AI extracts structured data from invoices arriving in inconsistent formats and channels, eliminating manual keying.",
        "business_value_baseline": 88,
        "technical_feasibility_baseline": 90,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 20,
        "time_to_value_baseline": 85,
    },
    "procure_to_pay:invoice_matching": {
        "use_case_name": "AI-Assisted 3-Way Match & Exception Resolution",
        "ai_capability": "Pattern matching + anomaly detection with human-in-the-loop review",
        "required_data": ["Invoice, PO, and goods receipt data", "Historical exception resolutions"],
        "description": "AI reconciles invoice, PO, and receipt data automatically and pre-classifies exceptions with a suggested resolution.",
        "business_value_baseline": 90,
        "technical_feasibility_baseline": 85,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 30,
        "time_to_value_baseline": 75,
    },
    "procure_to_pay:approval": {
        "use_case_name": "Intelligent Approval Routing",
        "ai_capability": "Predictive routing based on historical approval patterns",
        "required_data": ["Approval matrix", "Historical approval decisions"],
        "description": "AI routes exceptions and high-value invoices to the approver most likely to resolve them quickly, reducing queue time.",
        "business_value_baseline": 60,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 20,
        "time_to_value_baseline": 82,
    },
    # ---------------- Order-to-Cash ----------------
    "order_to_cash:order_capture": {
        "use_case_name": "AI Order Capture from Email/EDI",
        "ai_capability": "Document AI + intent extraction for multi-channel orders",
        "required_data": ["Historical orders", "Product catalog", "Email/EDI archive"],
        "description": "AI reads incoming order emails/EDI and populates order lines automatically, reducing manual entry errors.",
        "business_value_baseline": 65,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 25,
        "time_to_value_baseline": 78,
    },
    "order_to_cash:credit_check": {
        "use_case_name": "Predictive Credit Risk Scoring",
        "ai_capability": "Predictive scoring model on customer payment behavior",
        "required_data": ["AR aging history", "Payment history", "Credit bureau data"],
        "description": "AI scores customer credit risk in real time using historical payment behavior, speeding order release decisions.",
        "business_value_baseline": 58,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 30,
        "time_to_value_baseline": 75,
    },
    "order_to_cash:shipping": {
        "use_case_name": "AI-Optimized Carrier & Route Selection",
        "ai_capability": "Predictive optimization on cost/speed trade-offs",
        "required_data": ["Carrier rates", "Historical delivery performance"],
        "description": "AI recommends the optimal carrier and routing per shipment based on cost, speed, and reliability history.",
        "business_value_baseline": 50,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 20,
        "time_to_value_baseline": 70,
    },
    "order_to_cash:invoicing": {
        "use_case_name": "Automated Invoice Generation & Validation",
        "ai_capability": "Rules + anomaly detection on pricing/tax accuracy",
        "required_data": ["Delivery confirmations", "Pricing agreements", "Tax rules"],
        "description": "AI validates pricing, tax, and quantities before invoice issuance, catching errors before they reach the customer.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 20,
        "time_to_value_baseline": 80,
    },
    "order_to_cash:collections": {
        "use_case_name": "AI-Powered Collections Prioritization & Outreach",
        "ai_capability": "Predictive scoring + generative communication drafting",
        "required_data": ["AR aging", "Customer contact history", "Dispute records"],
        "description": "AI predicts which accounts are at risk of late payment and drafts tailored outreach, focusing collector time on the highest-risk accounts.",
        "business_value_baseline": 82,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 30,
        "time_to_value_baseline": 70,
    },
    "order_to_cash:cash_application": {
        "use_case_name": "Intelligent Cash Application Matching",
        "ai_capability": "Pattern matching across remittance formats",
        "required_data": ["Bank statements", "Remittance advice", "Open invoice ledger"],
        "description": "AI matches incoming payments to open invoices automatically, including partial and combined payments across inconsistent remittance formats.",
        "business_value_baseline": 85,
        "technical_feasibility_baseline": 88,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 20,
        "time_to_value_baseline": 82,
    },
    # ---------------- Record-to-Report ----------------
    "record_to_report:transaction_capture": {
        "use_case_name": "AI-Assisted Transaction Classification",
        "ai_capability": "Classification model on GL coding patterns",
        "required_data": ["Historical GL postings", "Sub-ledger feeds"],
        "description": "AI classifies and codes incoming transactions to the correct GL accounts based on historical patterns.",
        "business_value_baseline": 50,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 75,
    },
    "record_to_report:journal_entries": {
        "use_case_name": "Automated Journal Entry Generation",
        "ai_capability": "Rules + generative drafting for recurring/accrual entries",
        "required_data": ["Accrual schedules", "Allocation rules", "Prior period entries"],
        "description": "AI drafts recurring and accrual journal entries from prior-period patterns for accountant review and posting.",
        "business_value_baseline": 68,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 30,
        "time_to_value_baseline": 72,
    },
    "record_to_report:reconciliation": {
        "use_case_name": "AI-Assisted Account Reconciliation",
        "ai_capability": "Anomaly detection + matching across ledgers",
        "required_data": ["GL balances", "Bank statements", "Intercompany ledgers"],
        "description": "AI matches balances across accounts automatically and flags only genuine discrepancies for accountant investigation.",
        "business_value_baseline": 85,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 30,
        "time_to_value_baseline": 72,
    },
    "record_to_report:reporting": {
        "use_case_name": "AI-Generated Management Reporting & Variance Commentary",
        "ai_capability": "LLM-generated narrative grounded in financial data",
        "required_data": ["Consolidated financials", "Budget/forecast data", "Prior period commentary"],
        "description": "AI drafts variance commentary and management report narratives grounded in the period's actual financial data, for finance review.",
        "business_value_baseline": 62,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 35,
        "time_to_value_baseline": 78,
    },
    "record_to_report:compliance_review": {
        "use_case_name": "AI-Assisted Compliance & Audit Trail Review",
        "ai_capability": "Rules-based checks + anomaly flagging",
        "required_data": ["Regulatory checklists", "Audit trail", "Policy rules"],
        "description": "AI pre-screens transactions and disclosures against regulatory checklists, surfacing exceptions before human compliance review.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 70,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 40,
        "time_to_value_baseline": 65,
    },
    # ---------------- Customer Service ----------------
    "customer_service:ticket_intake": {
        "use_case_name": "AI-Powered Ticket Intake & Structuring",
        "ai_capability": "Natural language understanding on incoming queries",
        "required_data": ["Historical tickets", "Customer profile data"],
        "description": "AI structures free-text and voice queries into categorized, complete tickets at the point of intake.",
        "business_value_baseline": 58,
        "technical_feasibility_baseline": 85,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 20,
        "time_to_value_baseline": 85,
    },
    "customer_service:triage": {
        "use_case_name": "Intelligent Ticket Triage & Routing",
        "ai_capability": "Classification + intent detection",
        "required_data": ["Historical categorization", "SLA rules", "Ticket content"],
        "description": "AI classifies ticket intent and urgency and routes to the correct skill group automatically, cutting queue time.",
        "business_value_baseline": 72,
        "technical_feasibility_baseline": 90,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 20,
        "time_to_value_baseline": 88,
    },
    "customer_service:knowledge_search": {
        "use_case_name": "AI-Assisted Knowledge Retrieval (RAG)",
        "ai_capability": "Retrieval-augmented generation over knowledge base and case history",
        "required_data": ["Knowledge base articles", "Past case resolutions", "Product documentation"],
        "description": "AI retrieves and synthesizes the relevant knowledge-base articles and past resolutions for the agent's specific case.",
        "business_value_baseline": 80,
        "technical_feasibility_baseline": 88,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 35,
        "time_to_value_baseline": 75,
    },
    "customer_service:resolution": {
        "use_case_name": "AI-Assisted Resolution & Response Drafting",
        "ai_capability": "LLM reasoning grounded in retrieved knowledge, with human approval",
        "required_data": ["Case history", "Account data", "Resolution templates"],
        "description": "AI drafts a recommended resolution and response for agent review and approval before it reaches the customer.",
        "business_value_baseline": 78,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 50,
        "risk_baseline": 40,
        "time_to_value_baseline": 68,
    },
    "customer_service:escalation": {
        "use_case_name": "Predictive Escalation Detection",
        "ai_capability": "Predictive model on sentiment and case complexity",
        "required_data": ["Case severity signals", "Sentiment history", "Escalation outcomes"],
        "description": "AI flags cases likely to escalate before they do, routing them to specialists proactively.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 72,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 30,
        "time_to_value_baseline": 65,
    },
    "customer_service:closure": {
        "use_case_name": "Automated Follow-up & CSAT Analysis",
        "ai_capability": "Generative follow-up drafting + sentiment analysis",
        "required_data": ["CSAT survey data", "Case notes"],
        "description": "AI drafts closure follow-ups and analyzes CSAT feedback at scale to surface systemic service issues.",
        "business_value_baseline": 45,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 25,
        "risk_baseline": 15,
        "time_to_value_baseline": 85,
    },
    # ---------------- Inventory Management ----------------
    "inventory_management:demand_signal": {
        "use_case_name": "AI-Enhanced Demand Signal Sensing",
        "ai_capability": "Predictive modeling across POS, sales, and external signals",
        "required_data": ["POS data", "Sales orders", "Promotion calendar"],
        "description": "AI blends POS, order, and external signals into a real-time demand read, replacing lagging manual reports.",
        "business_value_baseline": 62,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 25,
        "time_to_value_baseline": 70,
    },
    "inventory_management:stock_monitoring": {
        "use_case_name": "AI-Driven Stock Level Alerts",
        "ai_capability": "Anomaly detection + predictive reorder-point calculation",
        "required_data": ["Inventory levels", "Historical stockouts", "Lead times"],
        "description": "AI dynamically adjusts reorder points and flags at-risk SKUs before stockouts occur.",
        "business_value_baseline": 65,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 20,
        "time_to_value_baseline": 78,
    },
    "inventory_management:replenishment_planning": {
        "use_case_name": "AI-Optimized Replenishment Planning",
        "ai_capability": "Predictive optimization balancing demand, lead time, and cost",
        "required_data": ["Demand forecast", "Supplier lead times", "Stock levels", "Cost data"],
        "description": "AI recommends optimal reorder quantities and timing, balancing service level against carrying cost.",
        "business_value_baseline": 82,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 50,
        "risk_baseline": 30,
        "time_to_value_baseline": 65,
    },
    "inventory_management:order_transfer": {
        "use_case_name": "AI-Assisted Transfer Order Generation",
        "ai_capability": "Rules-based generation from replenishment output",
        "required_data": ["Replenishment plan", "Transfer rules", "Supplier data"],
        "description": "AI converts replenishment decisions directly into purchase/transfer orders, removing a manual handoff.",
        "business_value_baseline": 48,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 20,
        "time_to_value_baseline": 80,
    },
    "inventory_management:receiving": {
        "use_case_name": "AI-Assisted Receiving Verification",
        "ai_capability": "Computer vision + document matching",
        "required_data": ["Delivery notes", "PO data", "Quality inspection images"],
        "description": "AI cross-checks received quantities and condition against PO data using document and image capture.",
        "business_value_baseline": 50,
        "technical_feasibility_baseline": 68,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 25,
        "time_to_value_baseline": 60,
    },
    "inventory_management:cycle_counting": {
        "use_case_name": "AI-Prioritized Cycle Counting",
        "ai_capability": "Predictive risk scoring on discrepancy likelihood",
        "required_data": ["System stock records", "Historical count variances"],
        "description": "AI prioritizes which SKUs/locations to count based on predicted discrepancy risk, cutting counting effort.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 20,
        "time_to_value_baseline": 72,
    },
    # ---------------- Demand Planning ----------------
    "demand_planning:historical_data": {
        "use_case_name": "AI-Automated Data Preparation for Forecasting",
        "ai_capability": "Data cleansing + anomaly detection",
        "required_data": ["Sales history", "Returns data", "Promotion calendar"],
        "description": "AI cleans and reconciles historical demand data automatically, removing a manual prep step before forecasting.",
        "business_value_baseline": 45,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 20,
        "time_to_value_baseline": 75,
    },
    "demand_planning:statistical_forecast": {
        "use_case_name": "AI-Driven Demand Forecasting",
        "ai_capability": "Machine-learning time-series forecasting",
        "required_data": ["Historical demand", "Seasonality patterns", "Product hierarchy"],
        "description": "AI generates statistically superior baseline forecasts versus traditional methods, updated continuously as new data arrives.",
        "business_value_baseline": 88,
        "technical_feasibility_baseline": 90,
        "implementation_complexity_baseline": 50,
        "risk_baseline": 25,
        "time_to_value_baseline": 62,
    },
    "demand_planning:market_overlay": {
        "use_case_name": "AI-Powered Market Signal Integration",
        "ai_capability": "LLM + predictive modeling on external/unstructured signals",
        "required_data": ["Market reports", "News/social signals", "Economic indicators"],
        "description": "AI ingests external market signals and quantifies their likely demand impact, augmenting the statistical baseline.",
        "business_value_baseline": 68,
        "technical_feasibility_baseline": 70,
        "implementation_complexity_baseline": 55,
        "risk_baseline": 35,
        "time_to_value_baseline": 55,
    },
    "demand_planning:consensus": {
        "use_case_name": "AI-Assisted Forecast Consensus Support",
        "ai_capability": "LLM-generated summary of forecast deltas and drivers",
        "required_data": ["Draft forecast", "Sales input", "Historical forecast accuracy"],
        "description": "AI summarizes where sales/finance input diverges from the statistical forecast and why, speeding consensus discussions.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 72,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 70,
    },
    # ---------------- Sales Operations ----------------
    "sales_operations:lead_capture": {
        "use_case_name": "AI-Assisted Lead Enrichment",
        "ai_capability": "Entity resolution + data enrichment",
        "required_data": ["Web form data", "Firmographic databases"],
        "description": "AI enriches inbound leads with firmographic and intent data automatically at the point of capture.",
        "business_value_baseline": 48,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 15,
        "time_to_value_baseline": 85,
    },
    "sales_operations:lead_qualification": {
        "use_case_name": "Predictive Lead Scoring",
        "ai_capability": "Predictive scoring model on conversion likelihood",
        "required_data": ["Historical conversion data", "Engagement history", "Firmographic data"],
        "description": "AI scores and ranks leads by conversion likelihood, focusing sales effort on the highest-propensity accounts.",
        "business_value_baseline": 78,
        "technical_feasibility_baseline": 85,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 25,
        "time_to_value_baseline": 72,
    },
    "sales_operations:opportunity_management": {
        "use_case_name": "AI-Assisted Deal Risk & Forecast Insights",
        "ai_capability": "Predictive modeling on pipeline signals",
        "required_data": ["CRM activity data", "Historical win/loss data"],
        "description": "AI flags at-risk deals and improves forecast accuracy by learning from historical pipeline behavior.",
        "business_value_baseline": 70,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 30,
        "time_to_value_baseline": 65,
    },
    "sales_operations:quote_generation": {
        "use_case_name": "AI-Generated Quotes & Proposals",
        "ai_capability": "Generative drafting from price books and templates",
        "required_data": ["Price books", "Discount rules", "Proposal templates", "Deal context"],
        "description": "AI assembles a compliant, tailored quote/proposal draft from deal context for rep review, cutting turnaround time.",
        "business_value_baseline": 68,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 20,
        "time_to_value_baseline": 82,
    },
    "sales_operations:contract_approval": {
        "use_case_name": "AI-Assisted Deal Desk Review",
        "ai_capability": "Rules + anomaly detection on margin/terms",
        "required_data": ["Margin thresholds", "Approval matrix", "Contract terms"],
        "description": "AI pre-screens non-standard terms and discounts against policy, flagging only genuine exceptions for deal desk review.",
        "business_value_baseline": 52,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 70,
    },
    # ---------------- Recruitment ----------------
    "recruitment:sourcing": {
        "use_case_name": "AI-Powered Candidate Sourcing",
        "ai_capability": "Semantic search + matching across candidate pools",
        "required_data": ["Job requirements", "Candidate databases", "Historical hires"],
        "description": "AI proactively surfaces and ranks candidates matching role requirements across job boards and internal databases.",
        "business_value_baseline": 60,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 30,
        "time_to_value_baseline": 65,
    },
    "recruitment:resume_screening": {
        "use_case_name": "AI-Assisted Resume Screening",
        "ai_capability": "Semantic matching between resumes and job requirements",
        "required_data": ["Resumes/CVs", "Job requirements", "Historical hiring outcomes"],
        "description": "AI shortlists candidates against role requirements consistently, with human recruiters making all final decisions.",
        "business_value_baseline": 75,
        "technical_feasibility_baseline": 85,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 45,
        "time_to_value_baseline": 78,
    },
    "recruitment:interview_scheduling": {
        "use_case_name": "AI Interview Scheduling Assistant",
        "ai_capability": "Constraint-based scheduling automation",
        "required_data": ["Panel calendars", "Candidate availability"],
        "description": "AI coordinates interview scheduling across candidates and panels automatically, removing email back-and-forth.",
        "business_value_baseline": 42,
        "technical_feasibility_baseline": 88,
        "implementation_complexity_baseline": 25,
        "risk_baseline": 10,
        "time_to_value_baseline": 90,
    },
    "recruitment:interview_assessment": {
        "use_case_name": "AI-Assisted Interview Summarization",
        "ai_capability": "LLM-generated structured summaries from interview notes",
        "required_data": ["Interview notes/transcripts", "Assessment scorecards"],
        "description": "AI summarizes interview feedback into structured, comparable scorecards to support (not replace) hiring decisions.",
        "business_value_baseline": 48,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 35,
        "time_to_value_baseline": 70,
    },
    # ---------------- Invoice Processing ----------------
    "invoice_processing:invoice_intake": {
        "use_case_name": "Multi-Channel Invoice Capture",
        "ai_capability": "Document AI across email, portal, EDI, and paper channels",
        "required_data": ["Historical invoices across channels", "Vendor master data"],
        "description": "AI captures and normalizes invoices arriving through every channel into a single structured queue.",
        "business_value_baseline": 78,
        "technical_feasibility_baseline": 88,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 20,
        "time_to_value_baseline": 82,
    },
    "invoice_processing:data_extraction": {
        "use_case_name": "Intelligent Document Processing (Field Extraction)",
        "ai_capability": "Document AI (layout-aware extraction) with confidence scoring",
        "required_data": ["Historical invoices", "Vendor master data", "Tax/PO reference rules"],
        "description": "AI extracts every key field from unstructured invoices with confidence scores, sending only low-confidence cases for human review.",
        "business_value_baseline": 92,
        "technical_feasibility_baseline": 92,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 20,
        "time_to_value_baseline": 85,
    },
    "invoice_processing:validation_coding": {
        "use_case_name": "AI-Assisted GL Coding",
        "ai_capability": "Classification model on historical coding patterns",
        "required_data": ["Chart of accounts", "Historical coding decisions"],
        "description": "AI predicts the correct GL account and cost center for each invoice line, learning from historical coding decisions.",
        "business_value_baseline": 70,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 78,
    },
    "invoice_processing:matching_exceptions": {
        "use_case_name": "AI-Assisted Invoice Matching & Exception Routing",
        "ai_capability": "Pattern matching + anomaly detection with human-in-the-loop review",
        "required_data": ["PO data", "Goods receipt data", "Historical exception resolutions"],
        "description": "AI performs automated matching and pre-classifies exceptions with a recommended resolution path.",
        "business_value_baseline": 85,
        "technical_feasibility_baseline": 85,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 30,
        "time_to_value_baseline": 75,
    },
    "invoice_processing:approval_routing": {
        "use_case_name": "Intelligent Approval Routing",
        "ai_capability": "Predictive routing based on historical approval patterns",
        "required_data": ["Approval matrix", "Historical approval decisions"],
        "description": "AI routes invoices to the approver most likely to act quickly based on historical behavior and delegation rules.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 20,
        "time_to_value_baseline": 82,
    },
    # ---------------- Claims Processing ----------------
    "claims_processing:claim_intake": {
        "use_case_name": "AI-Assisted Claim Intake (FNOL)",
        "ai_capability": "Conversational AI + structured extraction",
        "required_data": ["Claimant statements", "Policy data", "Historical claims"],
        "description": "AI captures a complete, structured first-notice-of-loss record from the claimant's own words, reducing intake time and errors.",
        "business_value_baseline": 62,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 30,
        "time_to_value_baseline": 75,
    },
    "claims_processing:coverage_verification": {
        "use_case_name": "Automated Coverage Verification",
        "ai_capability": "Document AI + rules engine over policy documents",
        "required_data": ["Policy documents", "Coverage rules", "Claim details"],
        "description": "AI checks claim details against policy terms automatically, flagging only ambiguous coverage cases for review.",
        "business_value_baseline": 68,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 30,
        "time_to_value_baseline": 78,
    },
    "claims_processing:documentation_collection": {
        "use_case_name": "AI-Assisted Documentation Collection",
        "ai_capability": "Generative outreach + document classification",
        "required_data": ["Required document checklists", "Claimant correspondence"],
        "description": "AI identifies missing documentation and drafts personalized follow-up requests to claimants and third parties.",
        "business_value_baseline": 58,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 72,
    },
    "claims_processing:damage_assessment": {
        "use_case_name": "AI-Assisted Damage Assessment",
        "ai_capability": "Computer vision on photos/inspection imagery",
        "required_data": ["Damage photos", "Historical assessment/repair cost data"],
        "description": "AI estimates damage severity and likely repair cost from submitted photos, accelerating initial assessment.",
        "business_value_baseline": 75,
        "technical_feasibility_baseline": 72,
        "implementation_complexity_baseline": 55,
        "risk_baseline": 35,
        "time_to_value_baseline": 58,
    },
    "claims_processing:fraud_screening": {
        "use_case_name": "AI-Powered Fraud Detection",
        "ai_capability": "Anomaly detection + network analysis on claim patterns",
        "required_data": ["Historical claim/fraud data", "External watchlists"],
        "description": "AI flags claims with anomalous patterns for investigation before payout, applied consistently at scale.",
        "business_value_baseline": 80,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 50,
        "risk_baseline": 35,
        "time_to_value_baseline": 62,
    },
    "claims_processing:adjudication": {
        "use_case_name": "AI-Assisted Claim Adjudication",
        "ai_capability": "Decision-support model grounded in policy limits and precedent",
        "required_data": ["Assessment results", "Policy limits", "Historical adjudication decisions"],
        "description": "AI recommends a claim outcome and payout range grounded in policy and precedent, with the final decision made by an adjuster.",
        "business_value_baseline": 78,
        "technical_feasibility_baseline": 70,
        "implementation_complexity_baseline": 55,
        "risk_baseline": 45,
        "time_to_value_baseline": 55,
    },
    # ---------------- Asset Maintenance ----------------
    "asset_maintenance:asset_monitoring": {
        "use_case_name": "Predictive Maintenance",
        "ai_capability": "Predictive modeling on IoT sensor and inspection data",
        "required_data": ["IoT sensor streams", "Historical failure data", "Maintenance logs"],
        "description": "AI predicts asset failure before it happens using sensor and inspection trends, shifting maintenance from reactive to predictive.",
        "business_value_baseline": 88,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 60,
        "risk_baseline": 30,
        "time_to_value_baseline": 50,
    },
    "asset_maintenance:work_order_creation": {
        "use_case_name": "AI-Automated Work Order Generation",
        "ai_capability": "Rules + classification from fault signals",
        "required_data": ["Fault codes", "Asset registry", "Maintenance history"],
        "description": "AI raises and pre-fills work orders automatically from detected fault signals, removing a manual step.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 20,
        "time_to_value_baseline": 78,
    },
    "asset_maintenance:maintenance_scheduling": {
        "use_case_name": "AI-Optimized Maintenance Scheduling",
        "ai_capability": "Predictive optimization balancing criticality, parts, and technician availability",
        "required_data": ["Technician availability", "Asset criticality scores", "Spare parts inventory"],
        "description": "AI sequences maintenance work orders to minimize downtime risk given technician and parts constraints.",
        "business_value_baseline": 72,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 50,
        "risk_baseline": 30,
        "time_to_value_baseline": 60,
    },
    "asset_maintenance:technician_dispatch": {
        "use_case_name": "AI-Assisted Technician Dispatch",
        "ai_capability": "Matching model on skills, location, and parts availability",
        "required_data": ["Technician skills/location data", "Parts availability"],
        "description": "AI matches the right technician and parts to each job automatically, reducing dispatch delays and repeat visits.",
        "business_value_baseline": 58,
        "technical_feasibility_baseline": 72,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 25,
        "time_to_value_baseline": 68,
    },
    "asset_maintenance:inspection_signoff": {
        "use_case_name": "AI-Assisted Inspection Compliance Check",
        "ai_capability": "Computer vision + checklist validation",
        "required_data": ["Inspection checklists", "Compliance standards", "Inspection photos"],
        "description": "AI cross-checks completed work against inspection checklists and compliance standards before sign-off.",
        "business_value_baseline": 48,
        "technical_feasibility_baseline": 68,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 30,
        "time_to_value_baseline": 60,
    },
    "asset_maintenance:documentation_compliance": {
        "use_case_name": "AI-Generated Compliance Documentation",
        "ai_capability": "Generative drafting grounded in maintenance logs",
        "required_data": ["Maintenance logs", "Regulatory requirements", "Warranty terms"],
        "description": "AI drafts regulatory and warranty documentation from maintenance logs, ready for technician sign-off.",
        "business_value_baseline": 52,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 25,
        "time_to_value_baseline": 75,
    },
    # ---------------- Loan Operations ----------------
    "loan_operations:application_intake": {
        "use_case_name": "AI-Assisted Application Intake",
        "ai_capability": "Document AI + structured extraction",
        "required_data": ["Application forms", "Identity documents", "Historical applications"],
        "description": "AI extracts and validates application data at intake, flagging incomplete submissions immediately.",
        "business_value_baseline": 58,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 78,
    },
    "loan_operations:document_verification": {
        "use_case_name": "Intelligent Document Verification (KYC)",
        "ai_capability": "Document AI + identity verification models",
        "required_data": ["KYC documents", "Income statements", "Historical verification outcomes"],
        "description": "AI verifies identity, income, and collateral documents automatically, escalating only ambiguous cases to human review.",
        "business_value_baseline": 82,
        "technical_feasibility_baseline": 88,
        "implementation_complexity_baseline": 45,
        "risk_baseline": 35,
        "time_to_value_baseline": 72,
    },
    "loan_operations:credit_risk_assessment": {
        "use_case_name": "AI-Enhanced Credit Risk Scoring",
        "ai_capability": "Predictive risk modeling beyond traditional bureau scores",
        "required_data": ["Credit bureau data", "Financial statements", "Historical loan performance"],
        "description": "AI enhances traditional credit scoring with a broader signal set to improve risk-adjusted approval decisions.",
        "business_value_baseline": 85,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 55,
        "risk_baseline": 45,
        "time_to_value_baseline": 55,
    },
    "loan_operations:underwriting_decision": {
        "use_case_name": "AI-Assisted Underwriting Decision Support",
        "ai_capability": "Decision-support model grounded in policy and risk assessment",
        "required_data": ["Risk assessment output", "Lending policy", "Pricing models"],
        "description": "AI recommends lending terms and decision grounded in policy and risk data, with underwriters retaining final authority.",
        "business_value_baseline": 80,
        "technical_feasibility_baseline": 70,
        "implementation_complexity_baseline": 55,
        "risk_baseline": 45,
        "time_to_value_baseline": 52,
    },
    "loan_operations:compliance_check": {
        "use_case_name": "AI-Powered AML & Compliance Screening",
        "ai_capability": "Anomaly detection + watchlist matching",
        "required_data": ["AML watchlists", "Regulatory rules", "Applicant data"],
        "description": "AI screens every application against AML and fair-lending rules consistently, reducing manual review load.",
        "business_value_baseline": 65,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 40,
        "risk_baseline": 40,
        "time_to_value_baseline": 68,
    },
    # ---------------- Content Operations ----------------
    "content_operations:content_briefing": {
        "use_case_name": "AI-Assisted Content Briefing",
        "ai_capability": "Predictive analytics + generative brief drafting",
        "required_data": ["Audience analytics", "Trend data", "Editorial calendar"],
        "description": "AI identifies high-potential content topics from audience data and drafts initial briefs for editorial review.",
        "business_value_baseline": 55,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 75,
    },
    "content_operations:content_creation": {
        "use_case_name": "AI-Assisted Content Drafting",
        "ai_capability": "Generative content drafting with human editorial finalization",
        "required_data": ["Style guidelines", "Source material", "Brand voice examples"],
        "description": "AI produces first-draft content variants for human writers/editors to refine, speeding production without removing editorial control.",
        "business_value_baseline": 65,
        "technical_feasibility_baseline": 82,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 35,
        "time_to_value_baseline": 78,
    },
    "content_operations:metadata_rights": {
        "use_case_name": "AI-Automated Metadata Tagging & Rights Checks",
        "ai_capability": "Classification + entity recognition over content assets",
        "required_data": ["Content assets", "Rights/licensing data", "Taxonomy"],
        "description": "AI tags content with structured metadata and cross-checks usage rights and licensing windows automatically.",
        "business_value_baseline": 72,
        "technical_feasibility_baseline": 85,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 30,
        "time_to_value_baseline": 78,
    },
    "content_operations:editorial_compliance": {
        "use_case_name": "AI-Assisted Editorial & Compliance Review",
        "ai_capability": "LLM review against brand and regulatory guidelines",
        "required_data": ["Brand guidelines", "Regulatory standards", "Content drafts"],
        "description": "AI pre-screens content drafts against brand and regulatory guidelines, flagging issues before human editorial sign-off.",
        "business_value_baseline": 68,
        "technical_feasibility_baseline": 78,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 35,
        "time_to_value_baseline": 75,
    },
    "content_operations:localization": {
        "use_case_name": "AI-Powered Localization",
        "ai_capability": "Neural machine translation + cultural adaptation review",
        "required_data": ["Source content", "Translation memory", "Regional guidelines"],
        "description": "AI translates and adapts content for regional markets at scale, with local reviewers validating tone and accuracy.",
        "business_value_baseline": 78,
        "technical_feasibility_baseline": 88,
        "implementation_complexity_baseline": 35,
        "risk_baseline": 25,
        "time_to_value_baseline": 82,
    },
    "content_operations:publishing_distribution": {
        "use_case_name": "AI-Optimized Publishing Scheduling",
        "ai_capability": "Predictive optimization on audience engagement timing",
        "required_data": ["Distribution schedule", "Engagement analytics", "Platform specs"],
        "description": "AI recommends optimal publishing timing and platform mix per content asset based on historical engagement.",
        "business_value_baseline": 50,
        "technical_feasibility_baseline": 75,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 15,
        "time_to_value_baseline": 80,
    },
    "content_operations:performance_monitoring": {
        "use_case_name": "AI-Powered Content Performance Analysis",
        "ai_capability": "Predictive analytics + LLM-generated insight summaries",
        "required_data": ["Engagement analytics", "Revenue data", "Content metadata"],
        "description": "AI surfaces which content attributes drive performance and summarizes actionable insight for future briefs.",
        "business_value_baseline": 52,
        "technical_feasibility_baseline": 80,
        "implementation_complexity_baseline": 30,
        "risk_baseline": 15,
        "time_to_value_baseline": 82,
    },
}


def get_template(process_id: str, stage_id: str) -> dict | None:
    return TEMPLATES.get(f"{process_id}:{stage_id}")
