"""Business process knowledge base.

This is the grounding layer referenced throughout PRODUCT.md and
BUSINESS_LOGIC.md: every process below is broken into real stages with
baseline ratings (0-100) for bottleneck potential, automation potential,
AI suitability, and business impact. The opportunity engine combines these
baselines with the user's actual assessment inputs (volume, error rate,
FTE, data readiness) — it never invents a use case that isn't rooted in a
stage defined here. See app/engines/opportunity_engine.py.

Rating scale (all 0-100, baseline / "typical" values before user-input
adjustment):
  manual_effort         Low / Medium / High (qualitative)
  bottleneck_potential  how often this stage is where delay accumulates
  automation_potential  how mechanically automatable the stage is today
  ai_suitability        how well the task fits current AI capabilities
                        (pattern recognition, language, prediction) vs.
                        needing pure human judgment
  business_impact       how much fixing this stage moves cost/speed/quality
"""

PROCESSES = {
    "procure_to_pay": {
        "id": "procure_to_pay",
        "name": "Procure-to-Pay",
        "category": "Procurement & Finance",
        "typical_functions": ["Procurement", "Finance"],
        "description": (
            "The end-to-end flow from raising a purchase requisition through "
            "receiving goods, matching invoices, and issuing payment to suppliers."
        ),
        "stages": [
            {
                "id": "requisition",
                "name": "Requisition",
                "description": "A business user raises a request to purchase goods or services against a budget.",
                "manual_effort": "Medium",
                "data_involved": ["Purchase requests", "Budget data", "Approval hierarchy"],
                "bottleneck_potential": 45,
                "automation_potential": 55,
                "ai_suitability": 50,
                "business_impact": 45,
            },
            {
                "id": "purchase_order",
                "name": "Purchase Order Creation",
                "description": "The requisition is converted into a formal purchase order sent to a selected supplier.",
                "manual_effort": "Medium",
                "data_involved": ["Supplier catalog", "Pricing agreements", "Requisition data"],
                "bottleneck_potential": 40,
                "automation_potential": 70,
                "ai_suitability": 55,
                "business_impact": 45,
            },
            {
                "id": "goods_receipt",
                "name": "Goods Receipt",
                "description": "Warehouse or receiving staff confirm that ordered goods arrived and record quantities/condition.",
                "manual_effort": "Medium",
                "data_involved": ["Delivery notes", "PO data", "Inspection records"],
                "bottleneck_potential": 50,
                "automation_potential": 60,
                "ai_suitability": 50,
                "business_impact": 50,
            },
            {
                "id": "invoice_receipt",
                "name": "Invoice Receipt",
                "description": "Supplier invoices arrive by email, PDF, EDI, or paper in inconsistent formats and must be captured into the system.",
                "manual_effort": "High",
                "data_involved": ["Supplier invoices (PDF/paper/EDI)", "Email attachments", "Vendor master data"],
                "bottleneck_potential": 80,
                "automation_potential": 85,
                "ai_suitability": 92,
                "business_impact": 80,
            },
            {
                "id": "invoice_matching",
                "name": "Invoice Matching",
                "description": "Invoice line items are reconciled against the purchase order and goods receipt (3-way match); mismatches are flagged as exceptions.",
                "manual_effort": "High",
                "data_involved": ["Invoice data", "PO data", "Goods receipt data", "Tolerance rules"],
                "bottleneck_potential": 85,
                "automation_potential": 75,
                "ai_suitability": 88,
                "business_impact": 85,
            },
            {
                "id": "approval",
                "name": "Approval",
                "description": "Exceptions and high-value invoices are routed to the right approver based on amount, category, and delegation rules.",
                "manual_effort": "Medium",
                "data_involved": ["Approval matrix", "Delegation rules", "Exception history"],
                "bottleneck_potential": 70,
                "automation_potential": 65,
                "ai_suitability": 68,
                "business_impact": 60,
            },
            {
                "id": "payment",
                "name": "Payment",
                "description": "Approved invoices are scheduled and paid according to supplier terms and cash-flow priorities.",
                "manual_effort": "Low",
                "data_involved": ["Payment terms", "Bank data", "Cash position"],
                "bottleneck_potential": 30,
                "automation_potential": 75,
                "ai_suitability": 45,
                "business_impact": 40,
            },
        ],
    },
    "order_to_cash": {
        "id": "order_to_cash",
        "name": "Order-to-Cash",
        "category": "Sales & Finance",
        "typical_functions": ["Sales", "Finance", "Customer Service"],
        "description": (
            "The flow from capturing a customer order through fulfillment, invoicing, "
            "and collecting payment."
        ),
        "stages": [
            {
                "id": "order_capture",
                "name": "Order Capture",
                "description": "Customer orders arrive via portal, EDI, email, or phone and must be entered accurately.",
                "manual_effort": "Medium",
                "data_involved": ["Order forms", "Email/EDI orders", "Product catalog", "Pricing"],
                "bottleneck_potential": 55,
                "automation_potential": 75,
                "ai_suitability": 78,
                "business_impact": 60,
            },
            {
                "id": "credit_check",
                "name": "Credit Check",
                "description": "The customer's credit standing and outstanding balance are reviewed before the order is released.",
                "manual_effort": "Low",
                "data_involved": ["Credit limits", "AR aging", "Payment history"],
                "bottleneck_potential": 45,
                "automation_potential": 80,
                "ai_suitability": 72,
                "business_impact": 45,
            },
            {
                "id": "order_fulfillment",
                "name": "Order Fulfillment",
                "description": "Warehouse operations pick, pack, and prepare the order based on inventory availability.",
                "manual_effort": "Medium",
                "data_involved": ["Inventory levels", "Warehouse locations", "Order priority"],
                "bottleneck_potential": 60,
                "automation_potential": 55,
                "ai_suitability": 50,
                "business_impact": 55,
            },
            {
                "id": "shipping",
                "name": "Shipping",
                "description": "Goods are dispatched, carriers are booked, and tracking information is generated.",
                "manual_effort": "Low",
                "data_involved": ["Carrier rates", "Delivery addresses", "Shipping rules"],
                "bottleneck_potential": 35,
                "automation_potential": 70,
                "ai_suitability": 55,
                "business_impact": 40,
            },
            {
                "id": "invoicing",
                "name": "Invoicing",
                "description": "An invoice is generated and sent to the customer based on delivered quantities and agreed pricing.",
                "manual_effort": "Medium",
                "data_involved": ["Delivery confirmation", "Pricing agreements", "Tax rules"],
                "bottleneck_potential": 45,
                "automation_potential": 80,
                "ai_suitability": 60,
                "business_impact": 55,
            },
            {
                "id": "collections",
                "name": "Collections",
                "description": "Overdue accounts are identified and customers are contacted to secure payment.",
                "manual_effort": "High",
                "data_involved": ["AR aging", "Customer contact history", "Dispute records"],
                "bottleneck_potential": 75,
                "automation_potential": 65,
                "ai_suitability": 82,
                "business_impact": 78,
            },
            {
                "id": "cash_application",
                "name": "Cash Application",
                "description": "Incoming payments are matched to open invoices, often across remittance formats with partial or combined payments.",
                "manual_effort": "High",
                "data_involved": ["Bank statements", "Remittance advice", "Open invoice ledger"],
                "bottleneck_potential": 78,
                "automation_potential": 80,
                "ai_suitability": 88,
                "business_impact": 75,
            },
        ],
    },
    "record_to_report": {
        "id": "record_to_report",
        "name": "Record-to-Report",
        "category": "Finance",
        "typical_functions": ["Finance"],
        "description": (
            "The financial close process: capturing transactions, reconciling accounts, "
            "consolidating results, and producing statutory and management reports."
        ),
        "stages": [
            {
                "id": "transaction_capture",
                "name": "Transaction Capture",
                "description": "Journal entries and sub-ledger transactions are recorded from source systems.",
                "manual_effort": "Medium",
                "data_involved": ["Sub-ledgers", "GL postings", "Source system feeds"],
                "bottleneck_potential": 40,
                "automation_potential": 70,
                "ai_suitability": 55,
                "business_impact": 45,
            },
            {
                "id": "journal_entries",
                "name": "Journal Entries",
                "description": "Manual and recurring journal entries (accruals, allocations, adjustments) are prepared and posted.",
                "manual_effort": "High",
                "data_involved": ["Accrual schedules", "Allocation rules", "Prior period data"],
                "bottleneck_potential": 65,
                "automation_potential": 70,
                "ai_suitability": 72,
                "business_impact": 65,
            },
            {
                "id": "reconciliation",
                "name": "Reconciliation",
                "description": "Balance sheet and intercompany accounts are reconciled to identify and resolve discrepancies.",
                "manual_effort": "High",
                "data_involved": ["GL balances", "Bank statements", "Intercompany ledgers"],
                "bottleneck_potential": 82,
                "automation_potential": 78,
                "ai_suitability": 85,
                "business_impact": 80,
            },
            {
                "id": "consolidation",
                "name": "Consolidation",
                "description": "Results from multiple entities/currencies are combined into group-level financials.",
                "manual_effort": "Medium",
                "data_involved": ["Entity financials", "FX rates", "Elimination rules"],
                "bottleneck_potential": 55,
                "automation_potential": 65,
                "ai_suitability": 50,
                "business_impact": 65,
            },
            {
                "id": "close",
                "name": "Close",
                "description": "The period is formally closed once all reconciliations and adjustments are finalized.",
                "manual_effort": "Medium",
                "data_involved": ["Close checklist", "Sign-off records"],
                "bottleneck_potential": 60,
                "automation_potential": 55,
                "ai_suitability": 45,
                "business_impact": 60,
            },
            {
                "id": "reporting",
                "name": "Reporting",
                "description": "Management reports, board packs, and variance commentary are compiled and distributed.",
                "manual_effort": "High",
                "data_involved": ["Consolidated financials", "Budget/forecast data", "Prior narratives"],
                "bottleneck_potential": 60,
                "automation_potential": 60,
                "ai_suitability": 80,
                "business_impact": 60,
            },
            {
                "id": "compliance_review",
                "name": "Compliance Review",
                "description": "Statutory, audit, and regulatory checks are performed before results are finalized.",
                "manual_effort": "Medium",
                "data_involved": ["Regulatory checklists", "Audit trail", "Policy rules"],
                "bottleneck_potential": 45,
                "automation_potential": 50,
                "ai_suitability": 55,
                "business_impact": 55,
            },
        ],
    },
    "customer_service": {
        "id": "customer_service",
        "name": "Customer Service",
        "category": "Customer Operations",
        "typical_functions": ["Customer Service"],
        "description": (
            "The flow from a customer raising an issue through resolution and closure, "
            "across contact center, chat, and email channels."
        ),
        "stages": [
            {
                "id": "ticket_intake",
                "name": "Ticket Intake",
                "description": "Customer queries arrive via phone, chat, email, or self-service and are logged as tickets.",
                "manual_effort": "Medium",
                "data_involved": ["Ticket text", "Customer profile", "Channel metadata"],
                "bottleneck_potential": 50,
                "automation_potential": 70,
                "ai_suitability": 85,
                "business_impact": 55,
            },
            {
                "id": "triage",
                "name": "Triage & Categorization",
                "description": "Tickets are classified by intent, urgency, and required skill group for routing.",
                "manual_effort": "High",
                "data_involved": ["Ticket content", "Historical categorization", "SLA rules"],
                "bottleneck_potential": 70,
                "automation_potential": 82,
                "ai_suitability": 90,
                "business_impact": 70,
            },
            {
                "id": "knowledge_search",
                "name": "Knowledge Search",
                "description": "Agents search internal knowledge bases and past cases to determine the correct resolution.",
                "manual_effort": "High",
                "data_involved": ["Knowledge base articles", "Past case history", "Product documentation"],
                "bottleneck_potential": 75,
                "automation_potential": 80,
                "ai_suitability": 92,
                "business_impact": 78,
            },
            {
                "id": "resolution",
                "name": "Resolution",
                "description": "The agent (or system) applies a fix, answer, or action to close the customer's issue.",
                "manual_effort": "Medium",
                "data_involved": ["Case history", "Product/account data", "Resolution templates"],
                "bottleneck_potential": 55,
                "automation_potential": 60,
                "ai_suitability": 75,
                "business_impact": 75,
            },
            {
                "id": "escalation",
                "name": "Escalation",
                "description": "Complex or sensitive cases are routed to specialist teams or supervisors.",
                "manual_effort": "Medium",
                "data_involved": ["Escalation criteria", "Specialist availability", "Case severity"],
                "bottleneck_potential": 45,
                "automation_potential": 55,
                "ai_suitability": 60,
                "business_impact": 50,
            },
            {
                "id": "closure",
                "name": "Follow-up & Closure",
                "description": "Resolution is confirmed with the customer, satisfaction is captured, and the ticket is closed.",
                "manual_effort": "Low",
                "data_involved": ["CSAT surveys", "Case notes"],
                "bottleneck_potential": 30,
                "automation_potential": 70,
                "ai_suitability": 65,
                "business_impact": 40,
            },
        ],
    },
    "inventory_management": {
        "id": "inventory_management",
        "name": "Inventory Management",
        "category": "Supply Chain",
        "typical_functions": ["Supply Chain", "Operations"],
        "description": (
            "The flow of monitoring stock levels, replenishing inventory, and receiving "
            "and counting goods across warehouses."
        ),
        "stages": [
            {
                "id": "demand_signal",
                "name": "Demand Signal Capture",
                "description": "Sales, POS, and forecast data are gathered to understand near-term demand.",
                "manual_effort": "Medium",
                "data_involved": ["POS data", "Sales orders", "Forecast history"],
                "bottleneck_potential": 45,
                "automation_potential": 65,
                "ai_suitability": 75,
                "business_impact": 55,
            },
            {
                "id": "stock_monitoring",
                "name": "Stock Monitoring",
                "description": "Current inventory levels are tracked against safety stock and reorder points.",
                "manual_effort": "Medium",
                "data_involved": ["Inventory levels", "Reorder points", "Warehouse locations"],
                "bottleneck_potential": 40,
                "automation_potential": 80,
                "ai_suitability": 78,
                "business_impact": 55,
            },
            {
                "id": "replenishment_planning",
                "name": "Replenishment Planning",
                "description": "Reorder quantities and timing are determined based on demand, lead time, and supplier constraints.",
                "manual_effort": "High",
                "data_involved": ["Demand forecast", "Supplier lead times", "Stock levels"],
                "bottleneck_potential": 70,
                "automation_potential": 70,
                "ai_suitability": 85,
                "business_impact": 78,
            },
            {
                "id": "order_transfer",
                "name": "Purchase / Transfer Order",
                "description": "Replenishment decisions are converted into purchase orders or inter-warehouse transfers.",
                "manual_effort": "Medium",
                "data_involved": ["Supplier data", "Transfer rules", "Replenishment plan"],
                "bottleneck_potential": 45,
                "automation_potential": 75,
                "ai_suitability": 55,
                "business_impact": 50,
            },
            {
                "id": "receiving",
                "name": "Receiving",
                "description": "Incoming stock is checked in, inspected, and recorded against expected quantities.",
                "manual_effort": "Medium",
                "data_involved": ["Delivery notes", "PO data", "Quality checks"],
                "bottleneck_potential": 55,
                "automation_potential": 60,
                "ai_suitability": 60,
                "business_impact": 50,
            },
            {
                "id": "putaway",
                "name": "Put-away",
                "description": "Received stock is moved to appropriate warehouse locations.",
                "manual_effort": "Low",
                "data_involved": ["Warehouse map", "Slotting rules"],
                "bottleneck_potential": 30,
                "automation_potential": 55,
                "ai_suitability": 45,
                "business_impact": 35,
            },
            {
                "id": "cycle_counting",
                "name": "Cycle Counting",
                "description": "Physical stock is periodically counted and reconciled against system records.",
                "manual_effort": "High",
                "data_involved": ["System stock records", "Physical count data"],
                "bottleneck_potential": 60,
                "automation_potential": 65,
                "ai_suitability": 70,
                "business_impact": 55,
            },
        ],
    },
    "demand_planning": {
        "id": "demand_planning",
        "name": "Demand Planning",
        "category": "Supply Chain",
        "typical_functions": ["Supply Chain", "Operations"],
        "description": (
            "The process of forecasting future demand and aligning supply, production, "
            "and inventory plans against it."
        ),
        "stages": [
            {
                "id": "historical_data",
                "name": "Historical Data Collection",
                "description": "Historical sales, promotions, and external data are gathered and cleaned.",
                "manual_effort": "Medium",
                "data_involved": ["Sales history", "Promotion calendar", "Returns data"],
                "bottleneck_potential": 45,
                "automation_potential": 70,
                "ai_suitability": 65,
                "business_impact": 50,
            },
            {
                "id": "statistical_forecast",
                "name": "Statistical Forecasting",
                "description": "Baseline forecasts are generated using statistical or machine-learning models.",
                "manual_effort": "Medium",
                "data_involved": ["Historical demand", "Seasonality patterns", "Product hierarchy"],
                "bottleneck_potential": 50,
                "automation_potential": 75,
                "ai_suitability": 92,
                "business_impact": 80,
            },
            {
                "id": "market_overlay",
                "name": "Market Intelligence Overlay",
                "description": "External signals (macro trends, weather, competitor moves, news) are layered onto the statistical baseline.",
                "manual_effort": "High",
                "data_involved": ["Market reports", "News/social signals", "Economic indicators"],
                "bottleneck_potential": 55,
                "automation_potential": 55,
                "ai_suitability": 82,
                "business_impact": 70,
            },
            {
                "id": "consensus",
                "name": "Consensus / Collaboration",
                "description": "Sales, marketing, and finance review and adjust the forecast collaboratively.",
                "manual_effort": "High",
                "data_involved": ["Draft forecast", "Sales input", "Finance targets"],
                "bottleneck_potential": 65,
                "automation_potential": 45,
                "ai_suitability": 55,
                "business_impact": 65,
            },
            {
                "id": "forecast_approval",
                "name": "Forecast Approval",
                "description": "The final consensus forecast is signed off by planning leadership.",
                "manual_effort": "Low",
                "data_involved": ["Consensus forecast", "Approval workflow"],
                "bottleneck_potential": 30,
                "automation_potential": 60,
                "ai_suitability": 40,
                "business_impact": 40,
            },
            {
                "id": "plan_distribution",
                "name": "Plan Distribution",
                "description": "The approved forecast is pushed into supply, production, and inventory planning systems.",
                "manual_effort": "Low",
                "data_involved": ["Approved forecast", "Downstream planning systems"],
                "bottleneck_potential": 25,
                "automation_potential": 80,
                "ai_suitability": 40,
                "business_impact": 45,
            },
        ],
    },
    "sales_operations": {
        "id": "sales_operations",
        "name": "Sales Operations",
        "category": "Sales & Marketing",
        "typical_functions": ["Sales", "Marketing"],
        "description": (
            "The flow from capturing a lead through qualification, opportunity management, "
            "and quote/contract handoff."
        ),
        "stages": [
            {
                "id": "lead_capture",
                "name": "Lead Capture",
                "description": "Inbound leads from web forms, campaigns, and events are logged into the CRM.",
                "manual_effort": "Low",
                "data_involved": ["Web forms", "Campaign data", "Event lists"],
                "bottleneck_potential": 35,
                "automation_potential": 85,
                "ai_suitability": 70,
                "business_impact": 45,
            },
            {
                "id": "lead_qualification",
                "name": "Lead Qualification",
                "description": "Leads are scored and prioritized based on fit and buying signals.",
                "manual_effort": "High",
                "data_involved": ["Firmographic data", "Engagement history", "Intent signals"],
                "bottleneck_potential": 60,
                "automation_potential": 70,
                "ai_suitability": 88,
                "business_impact": 72,
            },
            {
                "id": "opportunity_management",
                "name": "Opportunity Management",
                "description": "Qualified leads are progressed through pipeline stages with activities, forecasting, and risk tracking.",
                "manual_effort": "High",
                "data_involved": ["CRM opportunity data", "Activity logs", "Competitive intel"],
                "bottleneck_potential": 55,
                "automation_potential": 55,
                "ai_suitability": 75,
                "business_impact": 68,
            },
            {
                "id": "quote_generation",
                "name": "Quote / Proposal Generation",
                "description": "Pricing, discounting, and proposal documents are assembled for the customer.",
                "manual_effort": "High",
                "data_involved": ["Price books", "Discount rules", "Proposal templates"],
                "bottleneck_potential": 65,
                "automation_potential": 75,
                "ai_suitability": 82,
                "business_impact": 65,
            },
            {
                "id": "contract_approval",
                "name": "Contract & Pricing Approval",
                "description": "Non-standard terms and discounts are reviewed and approved by deal desk or finance.",
                "manual_effort": "Medium",
                "data_involved": ["Approval matrix", "Margin thresholds", "Contract terms"],
                "bottleneck_potential": 55,
                "automation_potential": 60,
                "ai_suitability": 60,
                "business_impact": 50,
            },
            {
                "id": "order_handoff",
                "name": "Order Handoff",
                "description": "The closed deal is handed off to order management/fulfillment systems.",
                "manual_effort": "Low",
                "data_involved": ["Signed contract", "Order details"],
                "bottleneck_potential": 30,
                "automation_potential": 75,
                "ai_suitability": 40,
                "business_impact": 40,
            },
        ],
    },
    "recruitment": {
        "id": "recruitment",
        "name": "Recruitment",
        "category": "Human Resources",
        "typical_functions": ["HR"],
        "description": (
            "The flow from an approved hiring requisition through sourcing, screening, "
            "interviewing, and onboarding handoff."
        ),
        "stages": [
            {
                "id": "requisition_approval",
                "name": "Requisition Approval",
                "description": "A hiring manager's request to fill a role is approved against headcount and budget.",
                "manual_effort": "Low",
                "data_involved": ["Headcount plan", "Budget data", "Job description"],
                "bottleneck_potential": 35,
                "automation_potential": 60,
                "ai_suitability": 40,
                "business_impact": 35,
            },
            {
                "id": "sourcing",
                "name": "Sourcing",
                "description": "Candidates are identified through job boards, referrals, and outreach.",
                "manual_effort": "High",
                "data_involved": ["Job boards", "Candidate databases", "Referral data"],
                "bottleneck_potential": 60,
                "automation_potential": 65,
                "ai_suitability": 80,
                "business_impact": 60,
            },
            {
                "id": "resume_screening",
                "name": "Resume Screening",
                "description": "Applications are screened against role requirements to shortlist candidates.",
                "manual_effort": "High",
                "data_involved": ["Resumes/CVs", "Job requirements", "Candidate profiles"],
                "bottleneck_potential": 75,
                "automation_potential": 75,
                "ai_suitability": 90,
                "business_impact": 70,
            },
            {
                "id": "interview_scheduling",
                "name": "Interview Scheduling",
                "description": "Interviews are coordinated across candidates, panels, and calendars.",
                "manual_effort": "Medium",
                "data_involved": ["Panel availability", "Candidate availability"],
                "bottleneck_potential": 55,
                "automation_potential": 85,
                "ai_suitability": 60,
                "business_impact": 45,
            },
            {
                "id": "interview_assessment",
                "name": "Interview & Assessment",
                "description": "Candidates are interviewed and evaluated against role competencies.",
                "manual_effort": "High",
                "data_involved": ["Interview notes", "Assessment scorecards"],
                "bottleneck_potential": 50,
                "automation_potential": 40,
                "ai_suitability": 55,
                "business_impact": 60,
            },
            {
                "id": "offer_background",
                "name": "Offer & Background Check",
                "description": "An offer is extended and background/reference checks are completed.",
                "manual_effort": "Medium",
                "data_involved": ["Offer terms", "Background check results"],
                "bottleneck_potential": 45,
                "automation_potential": 65,
                "ai_suitability": 45,
                "business_impact": 45,
            },
            {
                "id": "onboarding_handoff",
                "name": "Onboarding Handoff",
                "description": "The hired candidate's data is handed off to onboarding and IT provisioning.",
                "manual_effort": "Low",
                "data_involved": ["New hire data", "IT provisioning requests"],
                "bottleneck_potential": 30,
                "automation_potential": 75,
                "ai_suitability": 40,
                "business_impact": 35,
            },
        ],
    },
    "invoice_processing": {
        "id": "invoice_processing",
        "name": "Invoice Processing",
        "category": "Finance & Procurement",
        "typical_functions": ["Finance", "Procurement"],
        "description": (
            "The document-centric flow of receiving, extracting, validating, and routing "
            "supplier invoices for payment, independent of the broader P2P cycle."
        ),
        "stages": [
            {
                "id": "invoice_intake",
                "name": "Invoice Receipt",
                "description": "Invoices arrive across email, portal, EDI, and paper channels in inconsistent formats and layouts.",
                "manual_effort": "High",
                "data_involved": ["Email attachments", "Scanned paper invoices", "EDI feeds"],
                "bottleneck_potential": 75,
                "automation_potential": 85,
                "ai_suitability": 90,
                "business_impact": 75,
            },
            {
                "id": "data_extraction",
                "name": "Data Capture / Extraction",
                "description": "Key fields (vendor, amount, line items, tax, PO reference) are extracted from unstructured documents.",
                "manual_effort": "High",
                "data_involved": ["Invoice documents", "Vendor master data", "Tax rules"],
                "bottleneck_potential": 85,
                "automation_potential": 88,
                "ai_suitability": 95,
                "business_impact": 85,
            },
            {
                "id": "validation_coding",
                "name": "Validation & Coding",
                "description": "Extracted data is validated and coded to the correct GL account and cost center.",
                "manual_effort": "High",
                "data_involved": ["Chart of accounts", "Historical coding patterns", "Extracted invoice data"],
                "bottleneck_potential": 70,
                "automation_potential": 75,
                "ai_suitability": 85,
                "business_impact": 72,
            },
            {
                "id": "matching_exceptions",
                "name": "Matching & Exception Handling",
                "description": "Invoices are matched to POs/receipts, and mismatches are flagged and routed for resolution.",
                "manual_effort": "High",
                "data_involved": ["PO data", "Goods receipt data", "Tolerance rules"],
                "bottleneck_potential": 82,
                "automation_potential": 72,
                "ai_suitability": 85,
                "business_impact": 80,
            },
            {
                "id": "approval_routing",
                "name": "Approval Routing",
                "description": "Invoices requiring sign-off are routed to the correct approver based on amount and category.",
                "manual_effort": "Medium",
                "data_involved": ["Approval matrix", "Delegation of authority"],
                "bottleneck_potential": 60,
                "automation_potential": 70,
                "ai_suitability": 65,
                "business_impact": 55,
            },
            {
                "id": "payment_scheduling",
                "name": "Payment Scheduling",
                "description": "Approved invoices are scheduled for payment per supplier terms and cash priorities.",
                "manual_effort": "Low",
                "data_involved": ["Payment terms", "Cash position"],
                "bottleneck_potential": 30,
                "automation_potential": 75,
                "ai_suitability": 45,
                "business_impact": 40,
            },
        ],
    },
    "claims_processing": {
        "id": "claims_processing",
        "name": "Claims Processing",
        "category": "Insurance & Risk Operations",
        "typical_functions": ["Operations", "Customer Service"],
        "description": (
            "The flow from a claim being reported through verification, assessment, "
            "adjudication, and payout."
        ),
        "stages": [
            {
                "id": "claim_intake",
                "name": "Claim Intake (FNOL)",
                "description": "The first notice of loss is captured from the claimant across phone, app, or web channels.",
                "manual_effort": "Medium",
                "data_involved": ["Claimant statements", "Policy data", "Incident details"],
                "bottleneck_potential": 50,
                "automation_potential": 75,
                "ai_suitability": 80,
                "business_impact": 55,
            },
            {
                "id": "coverage_verification",
                "name": "Coverage Verification",
                "description": "The claim is checked against policy terms to confirm coverage applies.",
                "manual_effort": "Medium",
                "data_involved": ["Policy documents", "Coverage rules", "Claim details"],
                "bottleneck_potential": 55,
                "automation_potential": 80,
                "ai_suitability": 82,
                "business_impact": 60,
            },
            {
                "id": "documentation_collection",
                "name": "Documentation Collection",
                "description": "Supporting evidence (photos, reports, invoices, statements) is gathered from the claimant and third parties.",
                "manual_effort": "High",
                "data_involved": ["Photos/documents", "Third-party reports", "Correspondence"],
                "bottleneck_potential": 70,
                "automation_potential": 60,
                "ai_suitability": 75,
                "business_impact": 65,
            },
            {
                "id": "damage_assessment",
                "name": "Damage / Loss Assessment",
                "description": "The extent of loss or damage is assessed to determine claim value.",
                "manual_effort": "High",
                "data_involved": ["Inspection reports", "Photos", "Repair estimates"],
                "bottleneck_potential": 75,
                "automation_potential": 55,
                "ai_suitability": 78,
                "business_impact": 78,
            },
            {
                "id": "fraud_screening",
                "name": "Fraud Screening",
                "description": "Claims are screened for anomalies or patterns indicative of fraud before payout.",
                "manual_effort": "Medium",
                "data_involved": ["Claim history", "Fraud indicators", "External watchlists"],
                "bottleneck_potential": 55,
                "automation_potential": 65,
                "ai_suitability": 88,
                "business_impact": 70,
            },
            {
                "id": "adjudication",
                "name": "Adjudication & Approval",
                "description": "A final decision is made on the claim outcome and payout amount.",
                "manual_effort": "High",
                "data_involved": ["Assessment results", "Policy limits", "Fraud screening results"],
                "bottleneck_potential": 68,
                "automation_potential": 50,
                "ai_suitability": 70,
                "business_impact": 80,
            },
            {
                "id": "payment_closure",
                "name": "Payment & Closure",
                "description": "The approved payout is issued and the claim file is closed.",
                "manual_effort": "Low",
                "data_involved": ["Payment instructions", "Claim file"],
                "bottleneck_potential": 30,
                "automation_potential": 75,
                "ai_suitability": 45,
                "business_impact": 45,
            },
        ],
    },
    "asset_maintenance": {
        "id": "asset_maintenance",
        "name": "Asset Maintenance",
        "category": "Operations & Engineering",
        "typical_functions": ["Operations", "IT"],
        "description": (
            "The flow of monitoring physical assets, creating and scheduling work orders, "
            "and executing and documenting maintenance."
        ),
        "stages": [
            {
                "id": "asset_monitoring",
                "name": "Asset Monitoring",
                "description": "Sensor and inspection data are monitored to detect early signs of asset degradation.",
                "manual_effort": "Medium",
                "data_involved": ["IoT sensor data", "Inspection logs", "Asset history"],
                "bottleneck_potential": 45,
                "automation_potential": 70,
                "ai_suitability": 90,
                "business_impact": 75,
            },
            {
                "id": "work_order_creation",
                "name": "Work Order Creation",
                "description": "A maintenance work order is raised once an issue or scheduled requirement is identified.",
                "manual_effort": "Medium",
                "data_involved": ["Fault codes", "Asset registry", "Maintenance history"],
                "bottleneck_potential": 40,
                "automation_potential": 75,
                "ai_suitability": 70,
                "business_impact": 55,
            },
            {
                "id": "maintenance_scheduling",
                "name": "Maintenance Scheduling",
                "description": "Work orders are prioritized and scheduled against technician availability and asset criticality.",
                "manual_effort": "High",
                "data_involved": ["Technician availability", "Asset criticality", "Spare parts inventory"],
                "bottleneck_potential": 65,
                "automation_potential": 65,
                "ai_suitability": 82,
                "business_impact": 70,
            },
            {
                "id": "technician_dispatch",
                "name": "Technician Dispatch",
                "description": "The right technician with the right skills and parts is dispatched to the asset location.",
                "manual_effort": "Medium",
                "data_involved": ["Technician skills", "Location data", "Parts availability"],
                "bottleneck_potential": 50,
                "automation_potential": 60,
                "ai_suitability": 60,
                "business_impact": 55,
            },
            {
                "id": "repair_execution",
                "name": "Repair Execution",
                "description": "The technician performs the physical repair or maintenance activity.",
                "manual_effort": "High",
                "data_involved": ["Repair manuals", "Parts data", "Safety procedures"],
                "bottleneck_potential": 40,
                "automation_potential": 25,
                "ai_suitability": 45,
                "business_impact": 60,
            },
            {
                "id": "inspection_signoff",
                "name": "Inspection & Sign-off",
                "description": "Completed work is inspected and formally signed off as complete and safe.",
                "manual_effort": "Medium",
                "data_involved": ["Inspection checklists", "Compliance standards"],
                "bottleneck_potential": 35,
                "automation_potential": 55,
                "ai_suitability": 55,
                "business_impact": 50,
            },
            {
                "id": "documentation_compliance",
                "name": "Documentation & Compliance",
                "description": "Maintenance records are filed to meet regulatory and warranty documentation requirements.",
                "manual_effort": "Medium",
                "data_involved": ["Regulatory requirements", "Maintenance logs", "Warranty terms"],
                "bottleneck_potential": 45,
                "automation_potential": 70,
                "ai_suitability": 75,
                "business_impact": 55,
            },
        ],
    },
    "loan_operations": {
        "id": "loan_operations",
        "name": "Loan Operations",
        "category": "Banking & Financial Services",
        "typical_functions": ["Operations", "Finance"],
        "description": (
            "The flow from a loan application through verification, underwriting, "
            "and disbursement."
        ),
        "stages": [
            {
                "id": "application_intake",
                "name": "Application Intake",
                "description": "Loan applications and supporting documents are submitted via branch, portal, or broker.",
                "manual_effort": "Medium",
                "data_involved": ["Application forms", "Identity documents", "Income proofs"],
                "bottleneck_potential": 50,
                "automation_potential": 75,
                "ai_suitability": 82,
                "business_impact": 55,
            },
            {
                "id": "document_verification",
                "name": "Document Verification",
                "description": "Identity, income, and collateral documents are checked for completeness and authenticity.",
                "manual_effort": "High",
                "data_involved": ["KYC documents", "Income statements", "Property/collateral documents"],
                "bottleneck_potential": 78,
                "automation_potential": 80,
                "ai_suitability": 90,
                "business_impact": 78,
            },
            {
                "id": "credit_risk_assessment",
                "name": "Credit & Risk Assessment",
                "description": "The applicant's creditworthiness and risk profile are evaluated against lending policy.",
                "manual_effort": "High",
                "data_involved": ["Credit bureau data", "Financial statements", "Risk models"],
                "bottleneck_potential": 70,
                "automation_potential": 65,
                "ai_suitability": 85,
                "business_impact": 82,
            },
            {
                "id": "underwriting_decision",
                "name": "Underwriting Decision",
                "description": "A final lending decision and terms are determined based on risk assessment and policy.",
                "manual_effort": "High",
                "data_involved": ["Risk assessment", "Lending policy", "Pricing models"],
                "bottleneck_potential": 65,
                "automation_potential": 55,
                "ai_suitability": 75,
                "business_impact": 85,
            },
            {
                "id": "compliance_check",
                "name": "Compliance Check",
                "description": "Regulatory, AML, and fair-lending checks are performed before approval is finalized.",
                "manual_effort": "Medium",
                "data_involved": ["AML watchlists", "Regulatory rules", "Applicant data"],
                "bottleneck_potential": 55,
                "automation_potential": 70,
                "ai_suitability": 80,
                "business_impact": 65,
            },
            {
                "id": "disbursement",
                "name": "Disbursement",
                "description": "Approved funds are released to the borrower according to agreed terms.",
                "manual_effort": "Low",
                "data_involved": ["Approved terms", "Bank account details"],
                "bottleneck_potential": 30,
                "automation_potential": 80,
                "ai_suitability": 40,
                "business_impact": 45,
            },
        ],
    },
    "content_operations": {
        "id": "content_operations",
        "name": "Content Operations",
        "category": "Media & Publishing",
        "typical_functions": ["Marketing", "Operations"],
        "description": (
            "The flow from content briefing through creation, rights management, "
            "compliance review, localization, and publishing."
        ),
        "stages": [
            {
                "id": "content_briefing",
                "name": "Content Ideation & Briefing",
                "description": "Content requirements are defined based on editorial calendar and audience demand.",
                "manual_effort": "Medium",
                "data_involved": ["Editorial calendar", "Audience analytics", "Trend data"],
                "bottleneck_potential": 40,
                "automation_potential": 55,
                "ai_suitability": 78,
                "business_impact": 50,
            },
            {
                "id": "content_creation",
                "name": "Content Creation / Acquisition",
                "description": "Content is produced in-house or acquired/licensed from external providers.",
                "manual_effort": "High",
                "data_involved": ["Source content", "Licensing agreements", "Style guidelines"],
                "bottleneck_potential": 55,
                "automation_potential": 50,
                "ai_suitability": 80,
                "business_impact": 65,
            },
            {
                "id": "metadata_rights",
                "name": "Metadata Tagging & Rights Management",
                "description": "Content is tagged with metadata and checked against usage rights and licensing windows.",
                "manual_effort": "High",
                "data_involved": ["Content assets", "Rights/licensing data", "Taxonomy"],
                "bottleneck_potential": 75,
                "automation_potential": 78,
                "ai_suitability": 88,
                "business_impact": 72,
            },
            {
                "id": "editorial_compliance",
                "name": "Editorial Review & Compliance",
                "description": "Content is reviewed for quality, brand, and regulatory/content-standards compliance.",
                "manual_effort": "High",
                "data_involved": ["Brand guidelines", "Regulatory standards", "Content drafts"],
                "bottleneck_potential": 65,
                "automation_potential": 55,
                "ai_suitability": 82,
                "business_impact": 68,
            },
            {
                "id": "localization",
                "name": "Localization",
                "description": "Content is translated and adapted for regional markets and languages.",
                "manual_effort": "High",
                "data_involved": ["Source content", "Translation memory", "Regional guidelines"],
                "bottleneck_potential": 70,
                "automation_potential": 70,
                "ai_suitability": 90,
                "business_impact": 70,
            },
            {
                "id": "publishing_distribution",
                "name": "Publishing & Distribution",
                "description": "Approved content is scheduled and published across platforms and territories.",
                "manual_effort": "Medium",
                "data_involved": ["Distribution schedule", "Platform specs", "Rights windows"],
                "bottleneck_potential": 45,
                "automation_potential": 75,
                "ai_suitability": 55,
                "business_impact": 55,
            },
            {
                "id": "performance_monitoring",
                "name": "Performance Monitoring",
                "description": "Content performance is tracked to inform future briefs and catalog decisions.",
                "manual_effort": "Low",
                "data_involved": ["Engagement analytics", "Revenue data"],
                "bottleneck_potential": 25,
                "automation_potential": 70,
                "ai_suitability": 75,
                "business_impact": 45,
            },
        ],
    },
}


def get_process(process_id: str) -> dict:
    if process_id not in PROCESSES:
        raise KeyError(f"Unknown process_id: {process_id}")
    return PROCESSES[process_id]


def list_processes() -> list[dict]:
    return [
        {"id": p["id"], "name": p["name"], "category": p["category"], "description": p["description"]}
        for p in PROCESSES.values()
    ]
